### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by hopewise** [ohvitorino/ORTR#1]
Hello!

Is there any documentation for using this library? Is it working properly for large inputs?

**Comment by ohvitorino** [comment]
Hi @hopewise!

Not really. I developed this library in the context of one of my master's courses.
It's based on the paper "The open vehicle routing problem: Algorithms, large-scale test problems, and computational" https://www.sciencedirect.com/science/article/pii/S0305054805003515

Have a look at the paper and at the library tests, you'll be able to understand it I think.

Good luck!

**Comment by hopewise** [comment]
Thanks @ohvitorino I tried to access your paper, however they are asking me to pay in-order to see it!

**Comment by ohvitorino** [comment]
Yes, unfortunately it is not that easy to have access to some papers. I had access to this one through my university, because they have agreements with some publishers.

**Comment by hopewise** [comment]
never mind.. I understand
if you can figure out how to use Google OR-Tools to solve OVRP, that would be super helpful!
